---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: selfservice-project-{{ __PROJECT_NAME__ }}
  # create this resource in the argocd namespace so users can't do any
  # privilege escalation by getting access to other namespaces, etc.
  namespace: {{ argoNamespace }}
spec:
  destinations:
  - namespace: '{{ __PROJECT_NAME__ }}'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
{{~#each argoAppRepos }}
  - {{ this }}
{{~/each}}
