{{~#each argoAppRepos }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selfservice-project-{{ ../__PROJECT_NAME__ }}-{{ @key }}-prod

  # create this resource in the argocd namespace so users can't do any
  # privilege escalation by getting access to other namespaces, etc.
  namespace: {{ ../argoNamespace }}
spec:
  destination:
    namespace: {{ ../__PROJECT_NAME__ }}
    name: in-cluster
  project: selfservice-project-{{ ../__PROJECT_NAME__ }}
  source:
    path: prod
    repoURL: '{{ this }}'
    targetRevision: kubernetes-manifests
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  {{~/each}}