apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: selfservice-project-public-key-reader-{{ __PROJECT_NAME__ }}
  namespace: {{ __PROJECT_NAME__ }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - selfservice-project-public-key-{{ __PROJECT_NAME__ }}
  resources:
  - configmaps
  verbs:
  - get
  - list
