apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-key-creator-{{ __PROJECT_NAME__ }}
  namespace: argocd
  annotations:
    project.selfservice.innoq.io/apply: once
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssh-key-creator-{{ __PROJECT_NAME__ }}
subjects:
- kind: ServiceAccount
  name: ssh-key-creator-{{ __PROJECT_NAME__ }}
  namespace: argocd
