apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssh-public-key-reader
  namespace: argocd
rules:
- apiGroups:
  - ""
  resourceNames:
  - ssh-public-key
  resources:
  - configmaps
  verbs:
  - get
  - list
