apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssh-key-creator
  namespace: {{ __PROJECT_NAME__ }}
  annotations:
    project.selfservice.innoq.io/apply: once
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - create
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - ssh-key-creator
  resources:
  - roles
  - rolebindings
  verbs:
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - ssh-key-creator
  resources:
  - roles
  - rolebindigs
  verbs:
  - patch
- apiGroups:
  - ""
  resourceNames:
  - ssh-key-creator
  resources:
  - serviceaccounts
  verbs:
  - patch
- apiGroups:
  - batch
  resourceNames:
  - ssh-key-creator
  resources:
  - jobs
  verbs:
  - delete
