apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-public-key-reader
  namespace: {{ __PROJECT_NAME__ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssh-public-key-reader

# basically allow anyone to read the public key ... because: well ... it's public
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:unauthenticated
  apiGroup: rbac.authorization.k8s.io
