apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssh-key-creator
  namespace: {{ __PROJECT_NAME__ }}
  annotations:
    project.selfservice.innoq.io/apply: once
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssh-key-creator
subjects:
- kind: ServiceAccount
  name: ssh-key-creator
  namespace: {{ __PROJECT_NAME__ }}
