#!/bin/sh -ex
#
# Copyright 2021 Daniel Bornkessel
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cargo fmt
cargo fix --allow-dirty --allow-staged
cargo build --bin self-service-project-operator

./target/debug/self-service-project-operator --print-crd > manifests/projects.selfservice.innoq.io.yaml
./target/debug/self-service-project-operator --print-sample-project-manifest > manifests/project-sample.yaml

git diff --exit-code manifests/projects.selfservice.innoq.io.yaml
git diff --exit-code manifests/project-sample.yaml
