#!/bin/sh -ex
cargo fmt
cargo fix --allow-dirty

cargo run --bin self-service-project-operator -- \
  --print-crd > chart/self-service-operators/crds/crd.yaml

cargo run --bin self-service-project-operator -- --print-sample-project-manifest > self-service-project-manifest.yaml

git diff --exit-code chart/self-service-operators/crds/crd.yaml
git diff --exit-code self-service-project-manifest.yaml
