apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: selfservice:project:owner:{{ __PROJECT_NAME__ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: selfservice:project:owner:{{ __PROJECT_NAME__ }}
subjects:
{{~#each __PROJECT_OWNERS__ }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ this }}
{{~/each}}
