apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selfservice:project:owner
  namespace: {{ __PROJECT_NAME__ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
{{~#each __PROJECT_OWNERS__ }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ this }}
{{~/each}}
