{{ $visitedDirectories := dict }}
{{- range $path, $_ := .Files.Glob "manifest-secrets/*/*" }}
{{ $dir := dir $path }}
{{ if hasKey $visitedDirectories $dir }}{{ else }}
{{ $_ := set $visitedDirectories $dir "yes" }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    project.selfservice.innoq.io/operator-access: grant
  name: {{ base $dir }}
type: Opaque
data:
{{ ($.Files.Glob (printf "%s/*.yaml" (dir $path))).AsSecrets | indent 2 }}
{{- end }}{{ end }}
